### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by w71800**
潘威利

http://3.132.54.155:3000
http://3.132.54.155:3000/attraction/9

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
API is broken. MySQL connection is lost.

**Comment by w71800** [comment]
I can't actually find out the reason that cause the lost of connection.
But I try to add some error capture on the server, and if there's an error happened again, it will be showed on the page.

I've roughly and temporarily solve this problem by restarting the servers of MySQL and Python BE, and it should work now.

please check.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Again. Connection is lost.

You try to use connection pool but in a wrong way. You create connection pool and get one connection from the pool at start, re-use it after that. It just like you create a connection without pool. We should create connection pool at start. Only when request coming, we get one from the pool, use it, and close it. (Based on document, it means returning back. You can try to find it out.)

**Comment by w71800** [comment]
Thanks for help!

**Review by cwpeng — CHANGES_REQUESTED** [review]
This week's task is OK. But connection pool is not used in a right way still. Again, try to investigate every detail and concept carefully and fix it.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
