### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by w71800**
http://3.132.54.155:3000
http://3.132.54.155:3000/attraction/14
http://3.132.54.155:3000/booking

multi-attractions in /booking, has also been implemented
please check!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Show no booking message without any other form elements on /booking if there is no booking data.
2. I try to cancel delete booking action in confirm dialog but deleted anyway.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Show no booking message **without any other form elements** on /booking if there is no booking data. It's odd to show checkout form when there is no booking data.

**Comment by w71800** [comment]
Have fixed.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
