### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by w71800**
潘威利

http://3.132.54.155:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we scroll down and up quickly, your code will load the same page multiple times.

未命名-6

**Comment by w71800** [comment]
This bug has been fixed by adding a status to record if the request is pending.
Please check.

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
